#export ARCHS = armv6
#export TARGET=iphone:5.0:4.0
export ARCHS = armv7 armv7s arm64
export TARGET=iphone:7.0:4.3
GO_EASY_ON_ME=1

SUBPROJECT_NAME = minizip
minizip_C_FILES = ioapi.c mztools.c unzip.c zip.c

include ../../theos/makefiles/common.mk
include ../../theos/makefiles/subproject.mk
