export ARCHS = armv7
export TARGET=iphone:8.1:4.0
GO_EASY_ON_ME=1

SUBPROJECT_NAME = minizip
minizip_C_FILES = ioapi.c mztools.c unzip.c zip.c

include ../../theos/makefiles/common.mk
include ../../theos/makefiles/subproject.mk
