export ARCHS = armv7
GO_EASY_ON_ME=1
#export TARGET=iphone:5.0:4.0

SUBPROJECT_NAME = minizip
minizip_C_FILES = ioapi.c mztools.c unzip.c zip.c
#minizip_CFLAGS = -I../zlib -DHAVE_CONFIG_H -I. -DPNG_CONFIGURE_LIBPNG -DPNG_NO_PROGRESSIVE_READ -DPNG_NO_EASY_ACCESS

include ../theos/makefiles/common.mk
include ../theos/makefiles/subproject.mk