export ARCHS = armv6
GO_EASY_ON_ME=1
export TARGET=iphone:5.0:4.0

SUBPROJECT_NAME = minizip
minizip_C_FILES = ioapi.c mztools.c unzip.c zip.c

include ../theos/makefiles/common.mk
include ../theos/makefiles/subproject.mk